/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SingleRouteImport } from './routes/single'
import { Route as SameDocRouteImport } from './routes/same-doc'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AwarenessRouteImport } from './routes/awareness'
import { Route as IndexRouteImport } from './routes/index'

const SingleRoute = SingleRouteImport.update({
  id: '/single',
  path: '/single',
  getParentRoute: () => rootRouteImport,
} as any)
const SameDocRoute = SameDocRouteImport.update({
  id: '/same-doc',
  path: '/same-doc',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AwarenessRoute = AwarenessRouteImport.update({
  id: '/awareness',
  path: '/awareness',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/awareness': typeof AwarenessRoute
  '/compare': typeof CompareRoute
  '/same-doc': typeof SameDocRoute
  '/single': typeof SingleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/awareness': typeof AwarenessRoute
  '/compare': typeof CompareRoute
  '/same-doc': typeof SameDocRoute
  '/single': typeof SingleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/awareness': typeof AwarenessRoute
  '/compare': typeof CompareRoute
  '/same-doc': typeof SameDocRoute
  '/single': typeof SingleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/awareness' | '/compare' | '/same-doc' | '/single'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/awareness' | '/compare' | '/same-doc' | '/single'
  id: '__root__' | '/' | '/awareness' | '/compare' | '/same-doc' | '/single'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AwarenessRoute: typeof AwarenessRoute
  CompareRoute: typeof CompareRoute
  SameDocRoute: typeof SameDocRoute
  SingleRoute: typeof SingleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/single': {
      id: '/single'
      path: '/single'
      fullPath: '/single'
      preLoaderRoute: typeof SingleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/same-doc': {
      id: '/same-doc'
      path: '/same-doc'
      fullPath: '/same-doc'
      preLoaderRoute: typeof SameDocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awareness': {
      id: '/awareness'
      path: '/awareness'
      fullPath: '/awareness'
      preLoaderRoute: typeof AwarenessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AwarenessRoute: AwarenessRoute,
  CompareRoute: CompareRoute,
  SameDocRoute: SameDocRoute,
  SingleRoute: SingleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
