[install]
exact = true
linker = "isolated"
linkWorkspacePackages = true
minimumReleaseAge = 604800 # 7 days in seconds
minimumReleaseAgeExcludes = [
  "@types/bun",
  "typescript",
  "bun-types"
]

[install.security]
scanner = "@socketsecurity/bun-security-scanner"

[console]
depth=4

[test]
onlyFailures = true
concurrentTestGlob = "**/*"


[loader]
".wasm" = "file"
".data" = "file"
".node" = "file"

[run]
# equivalent to `bun --bun` for all `bun run` commands
bun = true